#!/bin/sh
# send dummy message 
# $Id: D,v 1.1 2002/08/28 20:06:52 rabbi Exp $

mixmaster=""
for i in $HOME/Mix/mixmaster mixmaster `which mixmaster 2>&1` $MIXPATH/mixmaster
do
  if [ -f "$x" -a -x "$i" ]
  then
    mixmaster=$i
  fi
done
if [ "$mixmaster" = "" ]
then
  echo "Please put the mixmaster binary somewhere in your PATH."
  exit 1
fi

$mixmaster -d
