#!/bin/sh
# post anonymous followup
# $Id: F,v 1.1 2002/08/28 20:06:52 rabbi Exp $

header()
{
  header=`cat $2 | sed '/^$/,$d' | grep -i "^$1:" | sed 's/^[a-zA-Z-]*: //'`
}

mixmaster=""
for i in $HOME/Mix/mixmaster mixmaster `which mixmaster 2>&1` $MIXPATH/mixmaster
do
  if [ -f "$i" -a -x "$i" ]
  then
    mixmaster=$i
  fi
done
if [ "$mixmaster" = "" ]
then
  echo "Please put the mixmaster binary somewhere in your PATH."
  exit 1
fi

TMP=/tmp/tmp.$$
MSG=/tmp/msg.$$

cat >$TMP

header From $TMP
WHO=$header

header Newsgroups $TMP
NEWSGROUP=$header

header Message-ID $TMP
REF=$header

header Subject $TMP
SUBJECT=$header

(
echo Newsgroups: $NEWSGROUP
echo References: $REF
echo Subject: Re: `echo $SUBJECT | sed 's/^Re: //'`
echo Chain: 0 0 replay 

echo
echo "$WHO writes:"
echo

sed '1,/^$/d;s/^/> /g' $TMP

echo

if [ -f ~/.anonsig ]
then
 echo "-- "
 cat ~/.anonsig
fi

) >$MSG
rm $TMP

$EDITOR $MSG </dev/tty

echo -n "Send message (y/n)? "
read ans </dev/tty

if [ "$ans" = "y" ]
then
  header Chain $MSG
  if [ "$header" = "" ]
  then
    CHAIN=""
  else
    CHAIN="-l $header"
  fi
  cat $MSG | grep -v '^Chain:' | $mixmaster -m $CHAIN
fi
rm $MSG
